from top.api.rest.VideoUpdateRequest import VideoUpdateRequest
from top.api.rest.WlbOutInventoryChangeNotifyRequest import WlbOutInventoryChangeNotifyRequest
from top.api.rest.WlbWaybillIPrintRequest import WlbWaybillIPrintRequest
from top.api.rest.DdAuctionRuleQueryRequest import DdAuctionRuleQueryRequest
from top.api.rest.ItemcatsAuthorizeGetRequest import ItemcatsAuthorizeGetRequest
from top.api.rest.RefundMessagesGetRequest import RefundMessagesGetRequest
from top.api.rest.WlbWaybillICancelRequest import WlbWaybillICancelRequest
from top.api.rest.ItemSkuPriceUpdateRequest import ItemSkuPriceUpdateRequest
from top.api.rest.SellercenterSubuserPermissionsRolesGetRequest import SellercenterSubuserPermissionsRolesGetRequest
from top.api.rest.WlbItemConsignmentDeleteRequest import WlbItemConsignmentDeleteRequest
from top.api.rest.HotelFixbookingRequest import HotelFixbookingRequest
from top.api.rest.WangwangEserviceNewevalsGetRequest import WangwangEserviceNewevalsGetRequest
from top.api.rest.TradeCloseRequest import TradeCloseRequest
from top.api.rest.DdStoreExportRequest import DdStoreExportRequest
from top.api.rest.SubuserDutyAddRequest import SubuserDutyAddRequest
from top.api.rest.FenxiaoGradeDeleteRequest import FenxiaoGradeDeleteRequest
from top.api.rest.UserSellerGetRequest import UserSellerGetRequest
from top.api.rest.FenxiaoCooperationGetRequest import FenxiaoCooperationGetRequest
from top.api.rest.LogisticsTraceSearchRequest import LogisticsTraceSearchRequest
from top.api.rest.DeliveryTemplateAddRequest import DeliveryTemplateAddRequest
from top.api.rest.WaimaiShopBusinessrulesGetRequest import WaimaiShopBusinessrulesGetRequest
from top.api.rest.TradeGetRequest import TradeGetRequest
from top.api.rest.TradeSnapshotGetRequest import TradeSnapshotGetRequest
from top.api.rest.SellercenterSubusersGetRequest import SellercenterSubusersGetRequest
from top.api.rest.WlbOrderitemPageGetRequest import WlbOrderitemPageGetRequest
from top.api.rest.WangwangEserviceLoginlogsGetRequest import WangwangEserviceLoginlogsGetRequest
from top.api.rest.TradeShippingaddressUpdateRequest import TradeShippingaddressUpdateRequest
from top.api.rest.ProductPropimgUploadRequest import ProductPropimgUploadRequest
from top.api.rest.WlbItemMapGetByExtentityRequest import WlbItemMapGetByExtentityRequest
from top.api.rest.UserrecommendItemsGetRequest import UserrecommendItemsGetRequest
from top.api.rest.LogisticsAddressReachableRequest import LogisticsAddressReachableRequest
from top.api.rest.FenxiaoCooperationTerminateRequest import FenxiaoCooperationTerminateRequest
from top.api.rest.WangwangEserviceGroupmemberGetRequest import WangwangEserviceGroupmemberGetRequest
from top.api.rest.DeliveryTemplatesGetRequest import DeliveryTemplatesGetRequest
from top.api.rest.PromotionCouponsGetRequest import PromotionCouponsGetRequest
from top.api.rest.SellercenterUserPermissionsGetRequest import SellercenterUserPermissionsGetRequest
from top.api.rest.FenxiaoProductMapDeleteRequest import FenxiaoProductMapDeleteRequest
from top.api.rest.WangwangEserviceEvalsGetRequest import WangwangEserviceEvalsGetRequest
from top.api.rest.ScitemUpdateRequest import ScitemUpdateRequest
from top.api.rest.WlbInventorylogQueryRequest import WlbInventorylogQueryRequest
from top.api.rest.VasSubscSearchRequest import VasSubscSearchRequest
from top.api.rest.HotelUpdateRequest import HotelUpdateRequest
from top.api.rest.MarketingPromotionsGetRequest import MarketingPromotionsGetRequest
from top.api.rest.SellercatsListGetRequest import SellercatsListGetRequest
from top.api.rest.WlbWaybillIGetRequest import WlbWaybillIGetRequest
from top.api.rest.WirelessBuntingItemShorturlCreateRequest import WirelessBuntingItemShorturlCreateRequest
from top.api.rest.WaimaiItemUpdateRequest import WaimaiItemUpdateRequest
from top.api.rest.WangwangEserviceAccountstatusGetRequest import WangwangEserviceAccountstatusGetRequest
from top.api.rest.RefundRefuseRequest import RefundRefuseRequest
from top.api.rest.LogisticsConsignOrderCreateandsendRequest import LogisticsConsignOrderCreateandsendRequest
from top.api.rest.FenxiaoRefundMessageAddRequest import FenxiaoRefundMessageAddRequest
from top.api.rest.ItemsCustomGetRequest import ItemsCustomGetRequest
from top.api.rest.HotelRoomAddRequest import HotelRoomAddRequest
from top.api.rest.PromotionMjsGetRequest import PromotionMjsGetRequest
from top.api.rest.ItemUpdateDelistingRequest import ItemUpdateDelistingRequest
from top.api.rest.InventoryInitialRequest import InventoryInitialRequest
from top.api.rest.SkusCustomGetRequest import SkusCustomGetRequest
from top.api.rest.TradeOrderskuUpdateRequest import TradeOrderskuUpdateRequest
from top.api.rest.WlbWaybillIProductRequest import WlbWaybillIProductRequest
from top.api.rest.PictureReplaceRequest import PictureReplaceRequest
from top.api.rest.FuwuSaleLinkGenRequest import FuwuSaleLinkGenRequest
from top.api.rest.FenxiaoProductMapAddRequest import FenxiaoProductMapAddRequest
from top.api.rest.TicketItemGetRequest import TicketItemGetRequest
from top.api.rest.UmpPromotionGetRequest import UmpPromotionGetRequest
from top.api.rest.LogisticsOrdersGetRequest import LogisticsOrdersGetRequest
from top.api.rest.FenxiaoGradesGetRequest import FenxiaoGradesGetRequest
from top.api.rest.WlbItemDeleteRequest import WlbItemDeleteRequest
from top.api.rest.HotelTypeAddRequest import HotelTypeAddRequest
from top.api.rest.WlbOrderPageGetRequest import WlbOrderPageGetRequest
from top.api.rest.LogisticsConsignResendRequest import LogisticsConsignResendRequest
from top.api.rest.TimeGetRequest import TimeGetRequest
from top.api.rest.TmallProductTemplateGetRequest import TmallProductTemplateGetRequest
from top.api.rest.ItemImgDeleteRequest import ItemImgDeleteRequest
from top.api.rest.FenxiaoDiscountAddRequest import FenxiaoDiscountAddRequest
from top.api.rest.RefundsApplyGetRequest import RefundsApplyGetRequest
from top.api.rest.ShopcatsListGetRequest import ShopcatsListGetRequest
from top.api.rest.FenxiaoProductSkusGetRequest import FenxiaoProductSkusGetRequest
from top.api.rest.FenxiaoGradeAddRequest import FenxiaoGradeAddRequest
from top.api.rest.FenxiaoDealerRequisitionorderRemarkUpdateRequest import FenxiaoDealerRequisitionorderRemarkUpdateRequest
from top.api.rest.MbcPromotionUseRequest import MbcPromotionUseRequest
from top.api.rest.FenxiaoProductcatDeleteRequest import FenxiaoProductcatDeleteRequest
from top.api.rest.WlbItemConsignmentQueryRequest import WlbItemConsignmentQueryRequest
from top.api.rest.FenxiaoProductcatsGetRequest import FenxiaoProductcatsGetRequest
from top.api.rest.DeliveryTemplateDeleteRequest import DeliveryTemplateDeleteRequest
from top.api.rest.ScitemGetRequest import ScitemGetRequest
from top.api.rest.TmallProductSpecsTicketGetRequest import TmallProductSpecsTicketGetRequest
from top.api.rest.TicketItemAddRequest import TicketItemAddRequest
from top.api.rest.WaimaiItemlistGetRequest import WaimaiItemlistGetRequest
from top.api.rest.FenxiaoLoginUserGetRequest import FenxiaoLoginUserGetRequest
from top.api.rest.HotelRoomImgDeleteRequest import HotelRoomImgDeleteRequest
from top.api.rest.FenxiaoProductQuantityUpdateRequest import FenxiaoProductQuantityUpdateRequest
from top.api.rest.ItemrecommendItemsGetRequest import ItemrecommendItemsGetRequest
from top.api.rest.SubuserDepartmentAddRequest import SubuserDepartmentAddRequest
from top.api.rest.FenxiaoRequisitionsGetRequest import FenxiaoRequisitionsGetRequest
from top.api.rest.DdReservedUpdateRequest import DdReservedUpdateRequest
from top.api.rest.VasSubscribeGetRequest import VasSubscribeGetRequest
from top.api.rest.WaimaiOrderSingleGetRequest import WaimaiOrderSingleGetRequest
from top.api.rest.SellercenterRolemembersGetRequest import SellercenterRolemembersGetRequest
from top.api.rest.TraderateExplainAddRequest import TraderateExplainAddRequest
from top.api.rest.DeliveryTemplateGetRequest import DeliveryTemplateGetRequest
from top.api.rest.TmallBrandcatPropinputGetRequest import TmallBrandcatPropinputGetRequest
from top.api.rest.WangwangEserviceEvaluationGetRequest import WangwangEserviceEvaluationGetRequest
from top.api.rest.PictureGetRequest import PictureGetRequest
from top.api.rest.TopatsTaskDeleteRequest import TopatsTaskDeleteRequest
from top.api.rest.SubuserDepartmentDeleteRequest import SubuserDepartmentDeleteRequest
from top.api.rest.WlbItemCombinationGetRequest import WlbItemCombinationGetRequest
from top.api.rest.ScitemMapAddRequest import ScitemMapAddRequest
from top.api.rest.ScitemMapDeleteRequest import ScitemMapDeleteRequest
from top.api.rest.LogisticsPartnersGetRequest import LogisticsPartnersGetRequest
from top.api.rest.LogisticsAddressSearchRequest import LogisticsAddressSearchRequest
from top.api.rest.WlbItemCombinationCreateRequest import WlbItemCombinationCreateRequest
from top.api.rest.FenxiaoDealerRequisitionorderQueryRequest import FenxiaoDealerRequisitionorderQueryRequest
from top.api.rest.TmallProductSpecsGetRequest import TmallProductSpecsGetRequest
from top.api.rest.InventoryAdjustExternalRequest import InventoryAdjustExternalRequest
from top.api.rest.ShopUpdateRequest import ShopUpdateRequest
from top.api.rest.InventoryStoreManageRequest import InventoryStoreManageRequest
from top.api.rest.AreasGetRequest import AreasGetRequest
from top.api.rest.PromotionActivityGetRequest import PromotionActivityGetRequest
from top.api.rest.HotelRoomGetRequest import HotelRoomGetRequest
from top.api.rest.SellercatsListUpdateRequest import SellercatsListUpdateRequest
from top.api.rest.TraderatesGetRequest import TraderatesGetRequest
from top.api.rest.WlbWaybillSearchRequest import WlbWaybillSearchRequest
from top.api.rest.FenxiaoCooperationProductcatAddRequest import FenxiaoCooperationProductcatAddRequest
from top.api.rest.ShoprecommendItemsGetRequest import ShoprecommendItemsGetRequest
from top.api.rest.WlbWaybillIFullupdateRequest import WlbWaybillIFullupdateRequest
from top.api.rest.CategoryrecommendItemsGetRequest import CategoryrecommendItemsGetRequest
from top.api.rest.ItemSkuUpdateRequest import ItemSkuUpdateRequest
from top.api.rest.FenxiaoDealerRequisitionorderRefuseRequest import FenxiaoDealerRequisitionorderRefuseRequest
from top.api.rest.ItemPropimgUploadRequest import ItemPropimgUploadRequest
from top.api.rest.ItemRecommendAddRequest import ItemRecommendAddRequest
from top.api.rest.SubuserDepartmentUpdateRequest import SubuserDepartmentUpdateRequest
from top.api.rest.WlbItemUpdateRequest import WlbItemUpdateRequest
from top.api.rest.ItemSkuGetRequest import ItemSkuGetRequest
from top.api.rest.SubuserDepartmentsGetRequest import SubuserDepartmentsGetRequest
from top.api.rest.VideosDeleteRequest import VideosDeleteRequest
from top.api.rest.ProductImgDeleteRequest import ProductImgDeleteRequest
from top.api.rest.WaimaiItemPicUploadRequest import WaimaiItemPicUploadRequest
from top.api.rest.TradeWaimaiOrdersGetRequest import TradeWaimaiOrdersGetRequest
from top.api.rest.PictureCategoryUpdateRequest import PictureCategoryUpdateRequest
from top.api.rest.FenxiaoOrderCreateDealerRequest import FenxiaoOrderCreateDealerRequest
from top.api.rest.HotelImageUploadRequest import HotelImageUploadRequest
from top.api.rest.TmallBrandcatControlGetRequest import TmallBrandcatControlGetRequest
from top.api.rest.VideosSearchRequest import VideosSearchRequest
from top.api.rest.ProductAddRequest import ProductAddRequest
from top.api.rest.TmallBrandcatSuiteconfGetRequest import TmallBrandcatSuiteconfGetRequest
from top.api.rest.ItemsListGetRequest import ItemsListGetRequest
from top.api.rest.TicketItemsGetRequest import TicketItemsGetRequest
from top.api.rest.FenxiaoRefundQueryRequest import FenxiaoRefundQueryRequest
from top.api.rest.FenxiaoDiscountsGetRequest import FenxiaoDiscountsGetRequest
from top.api.rest.WlbIcitemRegionsaleOperateRequest import WlbIcitemRegionsaleOperateRequest
from top.api.rest.ScitemMapBatchQueryRequest import ScitemMapBatchQueryRequest
from top.api.rest.ScitemMapQueryRequest import ScitemMapQueryRequest
from top.api.rest.LogisticsOrdersDetailGetRequest import LogisticsOrdersDetailGetRequest
from top.api.rest.WlbTmsorderQueryRequest import WlbTmsorderQueryRequest
from top.api.rest.WlbItemCombinationDeleteRequest import WlbItemCombinationDeleteRequest
from top.api.rest.HotelNameGetRequest import HotelNameGetRequest
from top.api.rest.ItemAddRequest import ItemAddRequest
from top.api.rest.DdAuctionRuleDeleteRequest import DdAuctionRuleDeleteRequest
from top.api.rest.ItemDeleteRequest import ItemDeleteRequest
from top.api.rest.TradeMemoUpdateRequest import TradeMemoUpdateRequest
from top.api.rest.FenxiaoOrdersGetRequest import FenxiaoOrdersGetRequest
from top.api.rest.FenxiaoDistributorsGetRequest import FenxiaoDistributorsGetRequest
from top.api.rest.PictureUploadRequest import PictureUploadRequest
from top.api.rest.FenxiaoRefundCreateRequest import FenxiaoRefundCreateRequest
from top.api.rest.WlbWaybillISearchRequest import WlbWaybillISearchRequest
from top.api.rest.WaimaiShopbycityGetRequest import WaimaiShopbycityGetRequest
from top.api.rest.WlbItemSynchronizeDeleteRequest import WlbItemSynchronizeDeleteRequest
from top.api.rest.ItemTemplatesGetRequest import ItemTemplatesGetRequest
from top.api.rest.WaimaiItemAddRequest import WaimaiItemAddRequest
from top.api.rest.SubuserEmployeeAddRequest import SubuserEmployeeAddRequest
from top.api.rest.TicketItemUpdateRequest import TicketItemUpdateRequest
from top.api.rest.SubuserInfoUpdateRequest import SubuserInfoUpdateRequest
from top.api.rest.FenxiaoOrderRemarkUpdateRequest import FenxiaoOrderRemarkUpdateRequest
from top.api.rest.FenxiaoOrderCloseRequest import FenxiaoOrderCloseRequest
from top.api.rest.WlbItemSynchronizeRequest import WlbItemSynchronizeRequest
from top.api.rest.ItemImgUploadRequest import ItemImgUploadRequest
from top.api.rest.TradesSoldGetRequest import TradesSoldGetRequest
from top.api.rest.FenxiaoProductSkuAddRequest import FenxiaoProductSkuAddRequest
from top.api.rest.AppipGetRequest import AppipGetRequest
from top.api.rest.HotelRoomUpdateRequest import HotelRoomUpdateRequest
from top.api.rest.MarketingPromotionKfcRequest import MarketingPromotionKfcRequest
from top.api.rest.FenxiaoProductSkuUpdateRequest import FenxiaoProductSkuUpdateRequest
from top.api.rest.TopatsResultGetRequest import TopatsResultGetRequest
from top.api.rest.WlbOrderdetailDateGetRequest import WlbOrderdetailDateGetRequest
from top.api.rest.FenxiaoProductsGetRequest import FenxiaoProductsGetRequest
from top.api.rest.FenxiaoProductGradepriceGetRequest import FenxiaoProductGradepriceGetRequest
from top.api.rest.ProductImgUploadRequest import ProductImgUploadRequest
from top.api.rest.ScitemOutercodeGetRequest import ScitemOutercodeGetRequest
from top.api.rest.ShopGetRequest import ShopGetRequest
from top.api.rest.WangwangEserviceStreamweigthsGetRequest import WangwangEserviceStreamweigthsGetRequest
from top.api.rest.ItemPriceUpdateRequest import ItemPriceUpdateRequest
from top.api.rest.WlbWaybillGetRequest import WlbWaybillGetRequest
from top.api.rest.FenxiaoDistributorItemsGetRequest import FenxiaoDistributorItemsGetRequest
from top.api.rest.WaimaiAddressGetRequest import WaimaiAddressGetRequest
from top.api.rest.ProductGetRequest import ProductGetRequest
from top.api.rest.DdReservedListRequest import DdReservedListRequest
from top.api.rest.ShoprecommendShopsGetRequest import ShoprecommendShopsGetRequest
from top.api.rest.ItemBarcodeUpdateRequest import ItemBarcodeUpdateRequest
from top.api.rest.LogisticsOnlineSendRequest import LogisticsOnlineSendRequest
from top.api.rest.ItemJointPropimgRequest import ItemJointPropimgRequest
from top.api.rest.LogisticsAddressAddRequest import LogisticsAddressAddRequest
from top.api.rest.WlbItemConsignmentPageGetRequest import WlbItemConsignmentPageGetRequest
from top.api.rest.FenxiaoProductAddRequest import FenxiaoProductAddRequest
from top.api.rest.InventoryStoreQueryRequest import InventoryStoreQueryRequest
from top.api.rest.ItempropsGetRequest import ItempropsGetRequest
from top.api.rest.SubuserDutyDeleteRequest import SubuserDutyDeleteRequest
from top.api.rest.LogisticsAddressRemoveRequest import LogisticsAddressRemoveRequest
from top.api.rest.PromotionLimitdiscountDetailGetRequest import PromotionLimitdiscountDetailGetRequest
from top.api.rest.LogisticsOfflineSendRequest import LogisticsOfflineSendRequest
from top.api.rest.LogisticsAddressModifyRequest import LogisticsAddressModifyRequest
from top.api.rest.WaimaiOrderIndexGetRequest import WaimaiOrderIndexGetRequest
from top.api.rest.WlbOrderCancelRequest import WlbOrderCancelRequest
from top.api.rest.LogisticsOnlineConfirmRequest import LogisticsOnlineConfirmRequest
from top.api.rest.TmallProductSpecPicUploadRequest import TmallProductSpecPicUploadRequest
from top.api.rest.FenxiaoProductUpdateRequest import FenxiaoProductUpdateRequest
from top.api.rest.ItemSkuDeleteRequest import ItemSkuDeleteRequest
from top.api.rest.InventoryIpcInventorydetailGetRequest import InventoryIpcInventorydetailGetRequest
from top.api.rest.ProductPropimgDeleteRequest import ProductPropimgDeleteRequest
from top.api.rest.WaimaiShopUpdateRequest import WaimaiShopUpdateRequest
from top.api.rest.WlbInventoryDetailGetRequest import WlbInventoryDetailGetRequest
from top.api.rest.WlbItemGetRequest import WlbItemGetRequest
from top.api.rest.FenxiaoProductImageDeleteRequest import FenxiaoProductImageDeleteRequest
from top.api.rest.ShopRemainshowcaseGetRequest import ShopRemainshowcaseGetRequest
from top.api.rest.WlbReplenishStatisticsRequest import WlbReplenishStatisticsRequest
from top.api.rest.HotelSoldHotelsIncrementGetRequest import HotelSoldHotelsIncrementGetRequest
from top.api.rest.WaimaiShopBusinessrulesUpdateRequest import WaimaiShopBusinessrulesUpdateRequest
from top.api.rest.FenxiaoProductcatAddRequest import FenxiaoProductcatAddRequest
from top.api.rest.ItemAnchorGetRequest import ItemAnchorGetRequest
from top.api.rest.WlbNotifyMessagePageGetRequest import WlbNotifyMessagePageGetRequest
from top.api.rest.SubuserEmployeeUpdateRequest import SubuserEmployeeUpdateRequest
from top.api.rest.PictureUpdateRequest import PictureUpdateRequest
from top.api.rest.ItemJointImgRequest import ItemJointImgRequest
from top.api.rest.HotelRoomsSearchRequest import HotelRoomsSearchRequest
from top.api.rest.InventoryQueryRequest import InventoryQueryRequest
from top.api.rest.TradeWaimaiRefuseRequest import TradeWaimaiRefuseRequest
from top.api.rest.TradesSoldIncrementGetRequest import TradesSoldIncrementGetRequest
from top.api.rest.PictureDeleteRequest import PictureDeleteRequest
from top.api.rest.WangwangEserviceOnlinetimeGetRequest import WangwangEserviceOnlinetimeGetRequest
from top.api.rest.AlibabaGeoipGetRequest import AlibabaGeoipGetRequest
from top.api.rest.HotelGetRequest import HotelGetRequest
from top.api.rest.WlbNotifyMessageConfirmRequest import WlbNotifyMessageConfirmRequest
from top.api.rest.HotelOrdersSearchRequest import HotelOrdersSearchRequest
from top.api.rest.FenxiaoCooperationUpdateRequest import FenxiaoCooperationUpdateRequest
from top.api.rest.ScitemAddRequest import ScitemAddRequest
from top.api.rest.SellercenterRoleAddRequest import SellercenterRoleAddRequest
from top.api.rest.PromotionLimitdiscountGetRequest import PromotionLimitdiscountGetRequest
from top.api.rest.PictureUserinfoGetRequest import PictureUserinfoGetRequest
from top.api.rest.WaimaiBcategoryGetRequest import WaimaiBcategoryGetRequest
from top.api.rest.SellercenterRolesGetRequest import SellercenterRolesGetRequest
from top.api.rest.FenxiaoGradeUpdateRequest import FenxiaoGradeUpdateRequest
from top.api.rest.HotelCityGetRequest import HotelCityGetRequest
from top.api.rest.DdMenuDetailRequest import DdMenuDetailRequest
from top.api.rest.FenxiaoTrademonitorGetRequest import FenxiaoTrademonitorGetRequest
from top.api.rest.VasOrderSearchRequest import VasOrderSearchRequest
from top.api.rest.SellercatsListAddRequest import SellercatsListAddRequest
from top.api.rest.WaimaiAgentOrderlistGetRequest import WaimaiAgentOrderlistGetRequest
from top.api.rest.TradeConfirmfeeGetRequest import TradeConfirmfeeGetRequest
from top.api.rest.AppstoreSubscribeGetRequest import AppstoreSubscribeGetRequest
from top.api.rest.ItemRecommendDeleteRequest import ItemRecommendDeleteRequest
from top.api.rest.HotelRoomImgUploadRequest import HotelRoomImgUploadRequest
from top.api.rest.TmallProductBooksAddRequest import TmallProductBooksAddRequest
from top.api.rest.TraderateAddRequest import TraderateAddRequest
from top.api.rest.WirelessBuntingShopShorturlCreateRequest import WirelessBuntingShopShorturlCreateRequest
from top.api.rest.ItemUpdateListingRequest import ItemUpdateListingRequest
from top.api.rest.ItemSkuAddRequest import ItemSkuAddRequest
from top.api.rest.RefundMessageAddRequest import RefundMessageAddRequest
from top.api.rest.PictureCategoryGetRequest import PictureCategoryGetRequest
from top.api.rest.WlbTradeorderGetRequest import WlbTradeorderGetRequest
from top.api.rest.SubusersGetRequest import SubusersGetRequest
from top.api.rest.PictureIsreferencedGetRequest import PictureIsreferencedGetRequest
from top.api.rest.WlbWaybillUpdateRequest import WlbWaybillUpdateRequest
from top.api.rest.DdAuctionRuleUpdateRequest import DdAuctionRuleUpdateRequest
from top.api.rest.HotelOrderGetRequest import HotelOrderGetRequest
from top.api.rest.LogisticsDummySendRequest import LogisticsDummySendRequest
from top.api.rest.InventoryInitialItemRequest import InventoryInitialItemRequest
from top.api.rest.SubuserFullinfoGetRequest import SubuserFullinfoGetRequest
from top.api.rest.TmallProductSpecAddRequest import TmallProductSpecAddRequest
from top.api.rest.WaimaiShopOpenRequest import WaimaiShopOpenRequest
from top.api.rest.RefundGetRequest import RefundGetRequest
from top.api.rest.ItemPropimgDeleteRequest import ItemPropimgDeleteRequest
from top.api.rest.TraderateListAddRequest import TraderateListAddRequest
from top.api.rest.FenxiaoRefundMessageGetRequest import FenxiaoRefundMessageGetRequest
from top.api.rest.SkusQuantityUpdateRequest import SkusQuantityUpdateRequest
from top.api.rest.TradesSoldIncrementvGetRequest import TradesSoldIncrementvGetRequest
from top.api.rest.ItemGetRequest import ItemGetRequest
from top.api.rest.WlbWlborderGetRequest import WlbWlborderGetRequest
from top.api.rest.TmallBrandcatSalesproGetRequest import TmallBrandcatSalesproGetRequest
from top.api.rest.SellercenterRoleInfoGetRequest import SellercenterRoleInfoGetRequest
from top.api.rest.FenxiaoProductSkuDeleteRequest import FenxiaoProductSkuDeleteRequest
from top.api.rest.WaimaiAddressOperateRequest import WaimaiAddressOperateRequest
from top.api.rest.FenxiaoProductImageUploadRequest import FenxiaoProductImageUploadRequest
from top.api.rest.ProductsGetRequest import ProductsGetRequest
from top.api.rest.HotelRoomsUpdateRequest import HotelRoomsUpdateRequest
from top.api.rest.FenxiaoProductcatUpdateRequest import FenxiaoProductcatUpdateRequest
from top.api.rest.TradeAmountGetRequest import TradeAmountGetRequest
from top.api.rest.WlbItemAuthorizationQueryRequest import WlbItemAuthorizationQueryRequest
from top.api.rest.RefundsReceiveGetRequest import RefundsReceiveGetRequest
from top.api.rest.FenxiaoProductGradepriceUpdateRequest import FenxiaoProductGradepriceUpdateRequest
from top.api.rest.HotelOrderFaceCheckRequest import HotelOrderFaceCheckRequest
from top.api.rest.DeliveryTemplateUpdateRequest import DeliveryTemplateUpdateRequest
from top.api.rest.HotelOrderFaceDealRequest import HotelOrderFaceDealRequest
from top.api.rest.WaimaiShopCloseRequest import WaimaiShopCloseRequest
from top.api.rest.HotelSoldOrdersIncrementGetRequest import HotelSoldOrdersIncrementGetRequest
from top.api.rest.WlbItemAuthorizationDeleteRequest import WlbItemAuthorizationDeleteRequest
from top.api.rest.WlbItemMapGetRequest import WlbItemMapGetRequest
from top.api.rest.WlbItemAddRequest import WlbItemAddRequest
from top.api.rest.HotelMatchFeedbackRequest import HotelMatchFeedbackRequest
from top.api.rest.HotelTypeNameGetRequest import HotelTypeNameGetRequest
from top.api.rest.DdAuctionRuleAddRequest import DdAuctionRuleAddRequest
from top.api.rest.TmallProductSpecGetRequest import TmallProductSpecGetRequest
from top.api.rest.PromotionMealGetRequest import PromotionMealGetRequest
from top.api.rest.FenxiaoCooperationAuditRequest import FenxiaoCooperationAuditRequest
from top.api.rest.TmallProductSuitespecsGetRequest import TmallProductSuitespecsGetRequest
from top.api.rest.MaQrcodeCommonCreateRequest import MaQrcodeCommonCreateRequest
from top.api.rest.ProductsSearchRequest import ProductsSearchRequest
from top.api.rest.MaPackcodeCreateRequest import MaPackcodeCreateRequest
from top.api.rest.FenxiaoOrderConfirmPaidRequest import FenxiaoOrderConfirmPaidRequest
from top.api.rest.ItempropvaluesGetRequest import ItempropvaluesGetRequest
from top.api.rest.WlbWaybillIQuerydetailRequest import WlbWaybillIQuerydetailRequest
from top.api.rest.WlbOrderstatusGetRequest import WlbOrderstatusGetRequest
from top.api.rest.ItemsOnsaleGetRequest import ItemsOnsaleGetRequest
from top.api.rest.FenxiaoDistributorProductsGetRequest import FenxiaoDistributorProductsGetRequest
from top.api.rest.WlbItemQueryRequest import WlbItemQueryRequest
from top.api.rest.FenxiaoDealerRequisitionorderGetRequest import FenxiaoDealerRequisitionorderGetRequest
from top.api.rest.FuwuScoresGetRequest import FuwuScoresGetRequest
from top.api.rest.WaimaiItemOperateRequest import WaimaiItemOperateRequest
from top.api.rest.FenxiaoOrderMessageAddRequest import FenxiaoOrderMessageAddRequest
from top.api.rest.FenxiaoDealerRequisitionorderModifyRequest import FenxiaoDealerRequisitionorderModifyRequest
from top.api.rest.WaimaiCategoryOperateRequest import WaimaiCategoryOperateRequest
from top.api.rest.FenxiaoDiscountUpdateRequest import FenxiaoDiscountUpdateRequest
from top.api.rest.WangwangEserviceReceivenumGetRequest import WangwangEserviceReceivenumGetRequest
from top.api.rest.TradeMemoAddRequest import TradeMemoAddRequest
from top.api.rest.KfcKeywordSearchRequest import KfcKeywordSearchRequest
from top.api.rest.WlbItemBatchQueryRequest import WlbItemBatchQueryRequest
from top.api.rest.WlbSubscriptionQueryRequest import WlbSubscriptionQueryRequest
from top.api.rest.WlbItemConsignmentCreateRequest import WlbItemConsignmentCreateRequest
from top.api.rest.HotelSoldTypesIncrementGetRequest import HotelSoldTypesIncrementGetRequest
from top.api.rest.WaimaiItemGetRequest import WaimaiItemGetRequest
from top.api.rest.VideosQueryRequest import VideosQueryRequest
from top.api.rest.ScitemQueryRequest import ScitemQueryRequest
from top.api.rest.LogisticsOnlineCancelRequest import LogisticsOnlineCancelRequest
from top.api.rest.FenxiaoDealerRequisitionorderCloseRequest import FenxiaoDealerRequisitionorderCloseRequest
from top.api.rest.WaimaiShopListRequest import WaimaiShopListRequest
from top.api.rest.InventoryAdjustTradeRequest import InventoryAdjustTradeRequest
from top.api.rest.ProductUpdateRequest import ProductUpdateRequest
from top.api.rest.TradeReceivetimeDelayRequest import TradeReceivetimeDelayRequest
from top.api.rest.TradeFullinfoGetRequest import TradeFullinfoGetRequest
from top.api.rest.ItemSkusGetRequest import ItemSkusGetRequest
from top.api.rest.TradeWaimaiConfirmRequest import TradeWaimaiConfirmRequest
from top.api.rest.HotelsSearchRequest import HotelsSearchRequest
from top.api.rest.FenxiaoRefundUpdateRequest import FenxiaoRefundUpdateRequest
from top.api.rest.WlbInventorySyncRequest import WlbInventorySyncRequest
from top.api.rest.ItemcatsGetRequest import ItemcatsGetRequest
from top.api.rest.DdTakeoutExportRequest import DdTakeoutExportRequest
from top.api.rest.SubuserDutysGetRequest import SubuserDutysGetRequest
from top.api.rest.WangwangEserviceNoreplynumGetRequest import WangwangEserviceNoreplynumGetRequest
from top.api.rest.WangwangEserviceAvgwaittimeGetRequest import WangwangEserviceAvgwaittimeGetRequest
from top.api.rest.WlbItemAuthorizationAddRequest import WlbItemAuthorizationAddRequest
from top.api.rest.ItemQuantityUpdateRequest import ItemQuantityUpdateRequest
from top.api.rest.WaimaiShopGetRequest import WaimaiShopGetRequest
from top.api.rest.LogisticsCompaniesGetRequest import LogisticsCompaniesGetRequest
from top.api.rest.VideoAddRequest import VideoAddRequest
from top.api.rest.ItemUpdateRequest import ItemUpdateRequest
from top.api.rest.LogisticsAddressReachablebatchGetRequest import LogisticsAddressReachablebatchGetRequest
from top.api.rest.TmallItemDescModulesGetRequest import TmallItemDescModulesGetRequest
from top.api.rest.InventoryOccupyAdjustRequest import InventoryOccupyAdjustRequest
from top.api.rest.WlbOrderConsignRequest import WlbOrderConsignRequest
from top.api.rest.ItemsInventoryGetRequest import ItemsInventoryGetRequest
from top.api.rest.ItemCspuMoveRequest import ItemCspuMoveRequest
from top.api.rest.SubuserDutyUpdateRequest import SubuserDutyUpdateRequest
from top.api.rest.FenxiaoDealerRequisitionorderCreateRequest import FenxiaoDealerRequisitionorderCreateRequest
from top.api.rest.HotelAddRequest import HotelAddRequest
from top.api.rest.WlbOrderCreateRequest import WlbOrderCreateRequest
from top.api.rest.TradePostageUpdateRequest import TradePostageUpdateRequest
from top.api.rest.PictureCategoryAddRequest import PictureCategoryAddRequest
from top.api.rest.AftersaleGetRequest import AftersaleGetRequest
from top.api.rest.FenxiaoRefundGetRequest import FenxiaoRefundGetRequest
from top.api.rest.FenxiaoDealerRequisitionorderAgreeRequest import FenxiaoDealerRequisitionorderAgreeRequest
from top.api.rest.TradeWaimaiGetRequest import TradeWaimaiGetRequest
